- name: Nginx installation
  hosts: localhost
 

  tasks:
    - name: Test parallel execution
      ansible.builtin.shell: |
        echo "Started {{ inventory_hostname }}"
        sleep 20
        echo "Finished {{ inventory_hostname }}"

