- name: Nginx installation
  hosts: test
 

  tasks:
    - name: Test parallel execution
      ansible.builtin.shell: 'echo "Started {{ inventory_hostname }} at $(date +%T)"; sleep 20; echo "Finished {{ inventory_hostname }} at $(date +%T)"'
      register: result

    - name: Show execution details
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"
