- name: Nginx installation
  hosts: localhost
 

  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx 
        state: present 

    - name: start nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes


