- name: create ec2 instances and update route53 records
  hosts: localhost
  connection: local # Ansible connects to the localhost

  vars:
    AMI_ID: "ami-0220d79f3f480ecf5"
    SG_ID: "sg-00f8aad7ab69831fd" # replace with your SG-ID
    ZONE_ID: "Z04223522WLWW3RAUWSAN" # this is your Hosted zone-ID
    DOMAIN_NAME: "devopsmegham.fun" # this is your domain name

    instances:
    - mondodb
    - redis
    - mysql

  tasks:
  - name: create ec2 instances 
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ SG_ID }}"
      image_id: "{{ AMI_ID }}"
      # tags:
      #   Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  # - name: print the ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"

  # - name: print public_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].public_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

  # - name: print private_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

    # create or update r53 records
  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ DOMAIN_NAME }}"
      record: "{{ item.item }}.{{ DOMAIN_NAME }}" # mongodb.devopsmegham.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"

# we are creating one record with public-ip only for frontend
  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ DOMAIN_NAME }}"
      record: "{{ DOMAIN_NAME }}" # devopsmegham.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    when: item.item == "frontend"
    loop: "{{ ec2_output.results }}"
    
