# these user variables will be used by all the services that are part of the project during the playbook execution
[all:vars] 
ansible_user=ec2-user
ansible_password=DevOps321

#Ansible roboshop services hosts 
[mongodb]
mongodb.devopsmegham.fun # DNS name of mongodb

[redis]
redis.devopsmegham.fun

