# these user variables will be used by all the services that are part of the project during the playbook execution
[all:vars] 
ansible_user=ec2-user
ansible_password=DevOps321

#Ansible roboshop services hosts 
[mongodb]
mongodb.devopsmegham.fun # DNS name of mongodb

[redis]
redis.devopsmegham.fun

[mysql]
mysql.devopsmegham.fun

[rabbitmq]
rabbitmq.devopsmegham.fun

[catalogue]
catalogue.devopsmegham.fun

[user]
user.devopsmegham.fun

[cart]
cart.devopsmegham.fun

[shipping]
shipping.devopsmegham.fun

[payment]
payment.devopsmegham.fun

[frontend]
frontend.devopsmegham.fun

