- name: mongodb server setup 
  hosts: mongodb
  become: yes

  tasks: 
    - name: copy mongodb repo 
      ansible.builtin.copy:
        src: ./mongo.repo
        dest: /etc/yum.repos.d/

    - name: install mongodb
      ansible.builtin.package:
        name: mongodb-org
        state: present

    - name: service start and auto restart on server reboot
      ansible.builtin.service:
        name: mongod 
        state: started
        enabled: yes

    - name: updaing config file 
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: 127.0.0.1
        replace: 0.0.0.0

    - name: service start
      ansible.builtin.service:
        name: mongod
        state: restarted

