# - name: Conditions
#   hosts: local
#   connection: local

#   vars:
#     NUMBER: 9

#   tasks:
#   - name: print whether the given number is less than 20
#     ansible.builtin.debug:
#       msg: "Given number is: {{ NUMBER }} less than 20"
#   when: NUMBER < 20

  

- name: Conditions
  hosts: local
  connection: local

  vars:
    NUMBER: 9

  tasks:
  - name: print whether the given number is less than 20
    ansible.builtin.debug:
      msg: "Given number is: {{ NUMBER }} less than 20"
  when: NUMBER < 20

  
  