- name: facts
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: Install nginix if OS is Redhat
    ansible.builtin.dnf:
      name: nginix
      state: latest
    when: ansible_os_family == "RedHat" # This first task will be executed since the condition is true.

  - name: Install nginix if OS is Redhat
    ansible.builtin.apt:
      name: nginix
      state: latest
    when: ansible_os_family == "Debian" # This second task will be skipped since the condition is false.