- name: Loops
  hosts: local
  connection: local # Ansible is connecting to localhost

  tasks: 
  - name: print names
    ansible.builtin.debug:
      msg: " Hello {{ item }}" # item is a reserved keyword that holds the value being processed in the Loop.

    loop:
    - Megham
    - Aaranya
    - Bujji
    - Sailendra