- name: Install packages
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: packages
    ansible.builtin.package:
      name: "{{ item }}" # {{ item }} → Used when loop contains simple values like below.
      state: present

    loop:
    - nginix
    - mysql
    - zip
