- name: Install packages
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest

    loop:
    - nginix
    - mysql
    - zip
