- name: filters
  hosts: local 
  connection: local # Ansible is connecting to the localhost

  vars:
    Goals: Learning, Job-switch, Family-happiness # string

  tasks:
  - name: default filter
    ansible.builtin.debug:
      msg: "name is: {{ NAME | default ('Megham') }} "

  - name: string to list conversion
    ansible.builtin.debug:
      msg: "conversion is: {{ Goals | split(',') }}"
