- name: filters
  hosts: local 
  connection: local # Ansible is connecting to the localhost


  tasks:
  - name: default function
    ansible.builtin.debug:
      msg: "name is: {{ NAME | default ('Megham') }} "