- name: filters
  hosts: local 
  connection: local # Ansible is connecting to the localhost

  vars:
    Goals: Learning, Job-switch, Family-happiness # string

    # dictinary/map
    Course:
      tool: ansible
      duration: 9
      days: 7

    Success:
      - key: patience
        value: 1
      - key: consistency
        value: 2
      - key: winner
        value: 3

  tasks:
  - name: default filter
    ansible.builtin.debug:
      msg: "name is: {{ NAME | default ('Megham') }} "

  - name: string to list conversion
    ansible.builtin.debug:
      msg: "conversion is: {{ Goals | split(',') }}"

  - name: dictionary/map to list conversion
    ansible.builtin.debug:
      msg: "conversion is: {{ Course | dict2items }}" # here, items--> list

  - name: list to dictionary/map conversion
    ansible.builtin.debug:
      msg: "conversion is: {{ Success | items2dict }}" # here, items--> list

  - name: read the data and take into a variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup( 'file', ./student.yaml) | from_yaml }}"


