- name: check user exist or not 
  hosts: local 
  connection: local # when you " connection: local ", Ansible connects to localhost.

  tasks:
  # ignore_errors handling method
  - name: user validation
    ansible.builtin.command: id Megham
    register: user_output
    ignore_errors: true

  - name: next task 
    ansible.builtin.debug:
      msg: " next task running: {{ user_output.stdout }}"

  # failed_when error handling method
  - name: root user
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: root_output

  - name: root user validation
    ansible.builtin.debug:
      msg: "{{ root_output.rc }}"
    failed_when: root_output.rc != 0

  - name: root user available
    ansible.builtin.debug:
      msg: "root user found: {{ root_output.stdout }}"
    
  # changed_when error handling method
  - name: check disk space
    ansible.builtin.command: df -h
    register: disk_output
    changed_when: false 

  - name: disk details
    ansible.builtin.debug:
      msg: "disk details are: {{ disk_output }}"

    # we are saying that this df -h just print the details and do not make any changes in the target server so don't show it as changed after the task is executed.


