- name: check user exist or not 
  hosts: local 
  connection: local # when you " connection: local ", Ansible connects to localhost.

  tasks:
  # ignore_errors handling method
  - name: user validation
    ansible.builtin.command: id Megham
    register: user_output
    ignore_errors: true

  - name: next task 
    ansible.builtin.debug:
      msg: " next task running: {{ user_output.stdout }}"

  # failed_when error handling method
  - name: root user
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: root_output


  - name: root user validation
    ansible.builtin.debug:
      msg: "{{ root_output.rc }}"
    failed_when: root_output.rc != 0


  - name: root user available
    ansible.builtin.debug:
      msg: "root user found: {{ root_output.stdout }}"
    
  

