- name: PLAY-1
  hosts: warrior
  become: yes

  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes



- name: PLAY-2
  hosts: frontend
  become: yes

  tasks:
  - name: install docker
    ansible.builtin.package:
      name: docker
      state: present
  
  - name: start docker
    ansible.builtin.service:
      name: docker
      state: started
      enabled: yes

