- name: play level variables
  hosts: local
  connection: local # Ansible is connecting to localhost

  # Below vars section is play level variables, play level variables can be used for multiple tasks
  vars:
    NAME: Bujji Megham
    HUSBAND: Aaranya

  tasks:
  - name: print the names
    ansible.builtin.debug:
      msg: " wife is: {{ NAME }}, and her Husband is: {{ HUSBAND }}" 