- name: task level variables
  hosts: local
  connection: local # Ansible is connecting to localhost

  tasks:
  - name: print Husband and wife names
    # Below vars section is task level variables, task variables are limited to only a specific task so   one task varibles cannot be used by other tasks 
    vars:
      NAME: Bujji Megham
      HUSBAND: Aaranya

    ansible.builtin.debug:
      msg: " wife is: {{ NAME }}, and her Husband is: {{ HUSBAND }}"
  
   