- name: play level variables
  hosts: local
  connection: local # Ansible is connecting to localhost

  # play level variables, play level variables can be used for multiple tasks
  vars:
    NAME: Bujji Megham
    HUSBAND: Aaranya

  tasks:
  - name: print the names
    # task level variables
    vars:
      HUSBAND: Sailendra

    ansible.builtin.debug:
      msg: " wife is: {{ NAME }}, and her Husband is: {{ HUSBAND }}" 


  # Task-level variables override play-level variables when both have the same variable name. that means When both task-level and play-level variables are declared with the same variable names but with different values then the first priority goes to task level variables only. so, here the output is "msg": " wife is: Bujji Megham, and her Husband is: Sailendra"