- name: variables from prompt
  hosts: local
  connection: local # Ansible is connecting to localhost

  vars_prompt:
  - name: USERNAME
    prompt: enter your name
    private: false # When you keep it as false it will shows the data on the screen while typing

  - name: PASSWORD
    prompt: enter the password
    private: true # When you keep it as true it will hide the data on the screen while typing

  tasks:
    - name: print the credentials
      ansible.builtin.debug:
        msg: "Hello, user is: {{ USERNAME }}, password is: {{ PASSWORD}}"
