[warrior]
100.53.132.70

[hardwork]
100.53.132.70
100.53.132.70

[family]
100.53.132.70

# Variable assignment for specific host
[frontend]
server1 ansible_host=100.53.132.70 NAME=Aaranya COURSE=Ansible
server2 ansible_host=100.53.132.71

[local]
localhost

# Variable assignment for group
[local:vars]
WIFE=Bujji Megham
HUSBAND=Aaranya

[hardwork:vars]
NAME=Aaranya
COURSE=Ansible
